#!/bin/sh
# lginput-native-hook installer for webOS 24+ (9.x)
# Usage: sh install.sh
#
# What this does:
#   - Installs lginput-hook.so to /home/root/
#   - Installs a boot startup script to /var/lib/webosbrew/init.d/
#   - Creates a default keybinds config if none exists
#   - Writes hook capability metadata for safe one-button capture
#   - Activates the hook immediately (no reboot needed)
#
# Requires: root access, Homebrew Channel installed

set -e

HOOK_SO="/home/root/lginput-hook.so"
INIT_SCRIPT="/var/lib/webosbrew/init.d/lginput-native-hook"
CONFIG_DIR="/home/root/.config/lginputhook"
CONFIG_FILE="$CONFIG_DIR/keybinds.json"
CAPABILITY_FILE="$CONFIG_DIR/hook-capabilities"
CAPTURE_FILE="$CONFIG_DIR/capture-request"
LEGACY_CAPTURE_FILE="/tmp/lginput-hook-capture"
ENV_DIR="/var/systemd/system/env"
ENV_FILE="$ENV_DIR/lginput2.env"

echo "[lginput-native-hook] Installing..."

# --- Extract embedded .so ---
echo "[lginput-native-hook] Extracting hook library..."
sed '1,/^PAYLOAD_START$/d' "$0" | base64 -d > "$HOOK_SO"
chmod 755 "$HOOK_SO"
echo "[lginput-native-hook] Installed: $HOOK_SO"

# --- Install boot init script ---
echo "[lginput-native-hook] Installing startup script..."
cat > "$INIT_SCRIPT" << 'INITEOF'
#!/bin/sh
# lginput-native-hook boot script
# Managed by lginput-native-hook installer

HOOK_SO="/home/root/lginput-hook.so"
ENV_DIR="/var/systemd/system/env"
ENV_FILE="$ENV_DIR/lginput2.env"

if [ ! -f "$HOOK_SO" ]; then
    echo "[lginput-native-hook] ERROR: $HOOK_SO not found, skipping" >&2
    exit 1
fi

mkdir -p "$ENV_DIR"
echo "LD_PRELOAD=$HOOK_SO" > "$ENV_FILE"
systemctl restart lginput2
sleep 2

if pgrep lginput2 > /dev/null; then
    echo "[lginput-native-hook] OK: lginput2 running with hook loaded"
else
    echo "[lginput-native-hook] ERROR: lginput2 failed to start, reverting" >&2
    rm -f "$ENV_FILE"
    systemctl restart lginput2
fi
INITEOF
chmod +x "$INIT_SCRIPT"
echo "[lginput-native-hook] Installed: $INIT_SCRIPT"

# --- Create default config if none exists ---
mkdir -p "$CONFIG_DIR"
chown 0:0 "$CONFIG_DIR"
chmod 700 "$CONFIG_DIR"
if [ ! -f "$CONFIG_FILE" ]; then
    cat > "$CONFIG_FILE" << 'CONFIGEOF'
{
    "reload": "1"
}
CONFIGEOF
    echo "[lginput-native-hook] Created default config: $CONFIG_FILE"
else
    echo "[lginput-native-hook] Existing config preserved: $CONFIG_FILE"
fi
chown 0:0 "$CONFIG_FILE"
chmod 600 "$CONFIG_FILE"

# Remove pending requests from this or the legacy capture protocol.
rm -f "$CAPTURE_FILE" "$LEGACY_CAPTURE_FILE"

cat > "$CAPABILITY_FILE" << 'CAPABILITYEOF'
capture_v2
CAPABILITYEOF
chown 0:0 "$CAPABILITY_FILE"
chmod 600 "$CAPABILITY_FILE"
echo "[lginput-native-hook] Wrote capabilities: $CAPABILITY_FILE"

# --- Activate immediately ---
echo "[lginput-native-hook] Activating hook..."
mkdir -p "$ENV_DIR"
echo "LD_PRELOAD=$HOOK_SO" > "$ENV_FILE"
systemctl restart lginput2
sleep 2

if pgrep lginput2 > /dev/null; then
    echo ""
    echo "[lginput-native-hook] Installation complete!"
    echo ""
    echo "  Configure buttons by editing:"
    echo "  $CONFIG_FILE"
    echo ""
    echo "  View live log with:"
    echo "  tail -f /tmp/lginput-hook-native.log"
    echo ""
    echo "  To uninstall, run: sh uninstall.sh"
else
    echo "[lginput-native-hook] ERROR: lginput2 failed to start after hook, reverting..." >&2
    rm -f "$ENV_FILE"
    systemctl restart lginput2
    exit 1
fi

exit 0
PAYLOAD_START
f0VMRgEBAQAAAAAAAAAAAAMAKAABAAAAAAAAADQAAADoGAAAAAIABTQAIAAJACgAFQAUAAYAAAA0AAAANAAAADQAAAAgAQAAIAEAAAQAAAAEAAAAAQAAAAAAAAAAAAAAAAAAAJsGAACbBgAABAAAAAAAAQABAAAAnAYAAJwGAQCcBgEANBAAADQQAAAFAAAAAAABAAEAAADQFgAA0BYCANAWAgDcAAAAMAkAAAYAAAAAAAEAAQAAAKwXAACsFwMArBcDAAgAAACYawAABgAAAAAAAQACAAAA0BYAANAWAgDQFgIAiAAAAIgAAAAGAAAABAAAAFLldGTQFgAA0BYCANAWAgDcAAAAMAkAAAQAAAABAAAAUeV0ZAAAAAAAAAAAAAAAAAAAAAAAAAAABgAAAAAAAAABAABwSAQAAEgEAABIBAAAQAAAAEAAAAAEAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAHAAAAAAAAAAAAAAASAAAAEAAAAAAAAAAAAAAAEgAAABkAAAAAAAAAAAAAABIAAAAgAAAAAAAAAAAAAAASAAAAJgAAAAAAAAAAAAAAEgAAAC0AAAAAAAAAAAAAABIAAAAyAAAAAAAAAAAAAAASAAAANwAAAAAAAAAAAAAAEgAAAD8AAAAAAAAAAAAAABIAAABQAAAAAAAAAAAAAAASAAAAVQAAAAAAAAAAAAAAEgAAAF0AAAAAAAAAAAAAABIAAABnAAAAAAAAAAAAAAASAAAAbAAAAAAAAAAAAAAAEgAAAHQAAAAAAAAAAAAAABIAAAB7AAAAAAAAAAAAAAASAAAAgQAAAAAAAAAAAAAAEgAAAIoAAAAAAAAAAAAAABIAAAABAAAAnAYBAJAKAAASAAsAAAACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgABAAEAAQCSAAAAEAAAAAAAAAAUaWkNAAACAJwAAAAAAAAAAQAAABMAAAABAAAAGgAAABAAAQATAAAAUbWoEBQAAAAUAAAADgAAAAoAAAAAAAAAAgAAABIAAAATAAAAAAAAAAUAAAAAAAAABAAAAAkAAAAAAAAAEQAAAAgAAAAGAAAAAAAAAAAAAAAAAAAADAAAAA0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwAAABAAAAALAAAADwAAAAB3cml0ZQBzbnByaW50ZgByZWFkbGluawBzdHJzdHIAY2xvc2UAdW5saW5rAG9wZW4AcmVhZABzdHJuY3B5AF9fZXJybm9fbG9jYXRpb24AdGltZQBzeXNjYWxsAHZzbnByaW50ZgBmb3JrAHdhaXRwaWQAZXhlY3ZlAF9leGl0AF9fZnhzdGF0AF9feHN0YXQAbGliYy5zby42AEdMSUJDXzIuNAAAAFQCAQCvRpuA3AwBAMQAAADUDQEAyAAAAMQOAQCvRpuA/A8BAMQAAAB0EAEAAQAAAKQQAQCAhJuACBEBAAEAAABkFwIAFgEAAGgXAgAWAgAAbBcCABYDAABwFwIAFgQAAHQXAgAWBQAAeBcCABYGAAB8FwIAFgcAAIAXAgAWCAAAhBcCABYJAACIFwIAFgoAAIwXAgAWCwAAkBcCABYMAACUFwIAFg0AAJgXAgAWDgAAnBcCABYPAACgFwIAFhAAAKQXAgAWEQAAqBcCABYSAABDmwGBsAKPhAAAAABDmwGBsLCPhAAAAABDmwGBsLCPhAAAAAB7ImlkIjoiJXMifQAvZGV2L3VpbnB1dAAvaG9tZS9yb290Ly5jb25maWcvbGdpbnB1dGhvb2svY2FwdHVyZS1yZXF1ZXN0AC9ob21lL3Jvb3QvLmNvbmZpZy9sZ2lucHV0aG9vay9rZXliaW5kcy5qc29uAGFjdGlvbgBQQVRIPS91c3IvYmluOi9iaW46L3Vzci9zYmluOi9zYmluAC1uAGx1bmE6Ly9jb20ud2Vib3MuYXBwbGljYXRpb25NYW5hZ2VyL2xhdW5jaAAvdG1wL2xnaW5wdXQtaG9vay1uYXRpdmUubG9nAGRpc2FibGUAa2V5Y29kZQByZXBsYWNlAC91c3IvYmluL2x1bmEtc2VuZABpZAAvcHJvYy9zZWxmL2ZkLyVkADEAIiVzIgBLRVkgY29kZT0ldSB2YWx1ZT0lZAoAQ0FQVFVSRSB0b2tlbj0lcyBjb2RlPSVkCgAA8E8t6RywjeJX303iGttN4gGgoOECQKDhABCg4RAAUuNvAgA6DwAU4m0CABrUCZ/lAACf5zigjeUAAFHhBAAAGsQJn+UAAJ/nAABQ4yMAABpjAgDqtImf5QCQoONEUI3iATCg4QiAj+ADYKDhAJCI5ZwJn+UAAI/gABCA5QUAoOGQKZ/lQBCg4wIgj+CgAwDrAuuN4gUAoOFHcI7inyCg4wcQoOGeAwDrAABQ40oCANoAkMfnBwCg4VwZn+UBEI/gmwMA6zigneUAAFDjAQAAEwYQoOEAAIjlAABQ40ACAAoCC1TjPgIAikRgjeIkcqDhLECN5QBAoOMAgKDjKBCN5TRwjeUWAADqBwCg4YwDAOsgCZ/lAACP4I0DAOs4oJ3lFAmf5RMeS+IAAI/gRQMA6wAAUON7AAAKAACg4wAAhuUEAIblAACg4zRwneUIAIblRGCN4gGAiOIBQITiBwBU4RACAAoKAKDhCJKG4AQSsOcIEobnBgCQ6QwAkOUMAInlcgD/5gIAUOMGAInp8f//CgEAUOPu//8aQICN5QxQmeW6gNnhdAif5QUgoOEAAI/gCBCg4TUCAOtkCJ/lAACf5zyAjeUIAFDhAwAAGgAAVeNOAAAKQICd5d7//+pIaJ/lAQBV40CAneUGYI/gy///GjgIn+UiG6DjAACP4FgDAOsBAHDjewEA2tgQS+IAcKDhEwMA6wAAUOO6//8ayAAb5Q8aAOICCVHjEgAQA7X//xrAABvlAABQ48QAGwUBAFADsP//GqwwG+UBAEPinwBQ46z//yoC643iBwCg4UcQjuKfIKDjMDCN5UEDAOsAoKDhBwCg4TIDAOswwJ3lAQBa46L//7oMAFrhoP//GgLrjeIAEKDjRwCO4gwQwOcC643iRwCO4gEA0OcJIEDiFwBS4wQAAIoTcADjATCg44BwQOMTAhfhXwEAGjAgQOIKAFLj3yAAIkEgQiIaAFIjAgAAOl8AUOMtAFATiP//Gk8AUeOG//8KASCB4hM+S+ICAFzhAQDD5wIQoOHj//8af///6hAHn+UAEODjQICd5QAAj+AAEIDli///6jBQjeXwUBvlCAef5QAAn+cFAFDhFQAAGgQAluUEERvlAQBQ4REAABoIAJblOKCd5URgjeI0cJ3lAQBQ4zAwneU8UJ3leP//uggXn+UBEI/gDBCB4gAgkeUFAFLhIAEACqwQgeIBAFDi+f//Gm7//+qkBp/lABCg4wAAj+DuAgDrAABQ42T//0oC643iBiqg40cQjuIFoKDhAFCg4eoCAOsAcKDhBQCg4QpQoOE4oJ3l2QIA6wEAV+NX//+6AuuN4gAAoONHoI7iBBEb5QfAiuAAUIblBwDK5wQQhuUIAIblAxCK4gQgiuIBoIriCjCg4QFwc+UiAFfjBgAACgEQgeIBIILiAaCK4gIwg+IMAFPh9f//msT//+oMAFrhiQAAKgAw2uUwMEPiCQBT44UAAIoAUKDjADDa5TpwQ+IKAHfjCQAAOgVxheABoIriARCB4gEgguKHMIPgDABa4TBQQ+Lz//86DKCg4XYAAOoiAFPjdAAAGgHgoOECEIriDABR4an//4oCMKDhAXD65QEQjuIBIILiewBX4/X//xoBEEriIBCN5QEQoOMMAFPhnv//igFwg+IBIFPlAWCg4QEQgeIHMKDhfQBS4/b//xoYAKDjAhBH4gAAjeUKAKDhHHCN5ThwS+IMYI3lEOCN5QcwoOEYwI3lFFCN5SQQjeUcJZ/lAiCP4NUBAOsAAFDjRwAACgwVn+UHAKDhCCCg4wEQj+BVAgDrAABQ4y4AAAr8FJ/lBwCg4QggoOMBEI/gTgIA6wAAUONEAAAK9BSf5QcAoOEHIKDjARCP4EcCAOsAAFDjMgAAGqAAoOMkEJ3lAACN5dgwS+LMJJ/lCgCg4QIgj+C2AQDrAABQ4ygAAAq4BJ/lAACP4AgAkOWfAFDjIwAAyqgkn+WsEKDjAKCg4wIgj+CQISfgFBCd5QEAgOIIAILlnyCg4xgAh+IMEIflAxCg4xAQh+XYEEviFKCH5V4CAOu3oMflEQAA6jgEn+UAAI/gCACQ5Z8AUOMMAADKKHSf5awQoOMUMJ3lACCg4wdwj+CQcSHgAQCA4ggAh+UMMIHlATCg4xggweUQMIHlFCCB5RwAneUBoEDiFASf5RjAneUAAI/gCACQ5QwAWuE2//8qoABQ42H//7oz///qHACd5dhgS+LII5/lMBCg48Qzn+UDUEDiAiCP4AYAoOEDMI/gGQIA6wYAoOHyAQDrAGCg4SAAneUIUI3lBQBQ4RAQneUMUJ3l4f//KgAAVuPf//8KBgCK4CQwneUDAFDh2///igFwoOHYEEviCgCg4QYgoOHpAQDrAABQ4wQAAAoBoIriARCH4gYAiuABUEXi8P//6iQAneUAAFrhzP//KgcwoOEAANrlOgBQ4wQAAAoBMIPiAaCK4gFQVeL4//8aw///6gggneUBAEPiAgBQ4b///yoDEKDhAQDT5DogQOIKAHLj9v//OghgneUwAEDiJCCd5QIAU+EJAAAqASDR5TowQuIKAHPjBQAAOgABgOABEIHiBgBR4YAAguAwAEDi9f//OrRin+VAgJ3lBmCP4AgQluWfAFHjpf//yqByn+WsIKDjADCg4wdwj+CRciLgGDDC5RQwneUMMILlAjCg4xQAguUBAIHiEDCC5QgAh+WX///q5QEA6wAAkOUCAFDjQf7/GkP+/+oEAJHlAQBQ40/+/woDAFDjBQAACgIAUONK/v8aCACR5QGAiOK6AMnhR/7/6gAAU+MMAIEC0gAAC0P+/+oTLkviAACg4wwAUeEBAMLnLP7/qgEAoOEC643iRyCO4gAg0ucJMELiFwBT4woAAIoTYADjAXCg44BgQOMXAxbhpGGf5QZgj+ADAAAKAQCA4gAAXOHv//8aGv7/6gAAUeMY/v8KOhBC4goAceMV/v86AHCg4wwAUOESAACqAuuN4kcQjuIAENHnOiBB4goAcuMMAAA6zTwM474hYeLMPEzjkiOD4KMBV+EG/v/KByGH4AEAgOIAAFzhghCB4DBwQeLt//8aEgAA6gwAUOEOAACqAuuN4kcQjuIAENHnCRBB4hcAUeMIAACKEzAA4wEgoOOAMEDjEgET4QMAAAoBAIDiAABc4fH//xoBAADqDABQ4ez9/xoAAKDjjwEA6wAAV+Ho/f/aEAGf5QAAj+B2AQDrCAGf5RMeS+I8IJ3lAACP4AAggOX4AJ/lAACP4D0AAOs4oJ3lRGCN4jRwneXr/f/qAABY4xIAAAooEJ3lRCCN4ggyoOEEAKDjewEA6wAAUOMsEJ3lABCgQQEAoOEc0Evi8I+96DigneUGEKDhBACg4wogoOEEMKDhbwEA6xzQS+Lwj73oLACd5RzQS+Lwj73o2BACAMwQAgCsEAIAlBACACf//v/o/f7/G/7+/1APAgDwDQIALA8CALj8/v+ICAIAnP3+/7f9/v/gDQIAP/v+/+T5/v89+v7/AAsCAOAKAgAx+v7/Jvn+/+X4/v9kCQIASAkCAOH5/v8I+v7/XAsCAEALAgCsCgIAoA0CAED1/v+IBwIATfb+/wzQTeLwSC3pELCN4lffTeIAUKDhCACL4g4AgOgIMIviXACN4gEcoOMFIKDhWDCN5QFMoOM+AQDrAQBQ4xkAALoBDFDjQRwI4wBAoDGkAJ/laS+g4wAAj+AdAQDrAQBw4wkAANoNEKDhAFCg4dgAAOsAAFDjEACdBRIAEAMNAAAKBQCg4QoBAOsDAADqHAEA6wAAkOUCAFDjAgAAClgAn+UAAI/gBgEA6xDQS+LwSL3oDNCN4h7/L+EPCgDiAglQ4xgAnQUAAFAD7P//GhQAneUBAFDj6f//GlwgjeIEAKDjBRCg4QQwoOENAQDrBQCg4e8AAOvr///qgPT+/zT0/v/wSC3pELCN4iveTeIAQKDhCwEA6wAAUOMIAAAKAQBQ4wQAALoAEKDjACCg4xDQS+LwSL3oBgEA6hDQS+LwiL3o/wAA6wAAUOMiAAAaFV5L4gQQoOEFAKDhdgAA63wgn+UgQI3iFR6g4wUwoOECII/gBACg4cIAAOsAEKDjGECN5RwQjeUNIKDhVACf5QAAj+AUAI3lTACf5QAAj+AQAI3lRACf5QAAj+AMAI3lPACf5QQQjeUAAI/gCACN5TAQn+UBEI/gABCN5QgQjeLkAADrfwCg4+YAAOsAAKDj5AAA65zy/v8d8/7/mPP+/wLz/v9V8/7/w/L+//BPLekcsI3iNNBN4gOAoOECMKDhICGf5QRAjeIBUKDhAHCg4QIgj+AEAKDhMBCg45UAAOsEAKDhbgAA6wCQoOMFAFfhOQAAKgBAoOEAAFDjNgAACgQAh+AFAFDhMwAAigigm+UEYI3iBwCg4QYQoOEEIKDhaAAA6wAAUOMEAAAKAXCH4gQAh+AFAFDh9f//miYAAOoFAFfhJAAAKgAA1+U6AFDjAwAACgFwh+IFAFfh+f//Gh0AAOoBAIfiBQBQ4RoAACoBENDkIgBR4/r//xoFAFDhFQAAKgAQoOMAkKDjCgAA6gEggOIFAFLhAgCgMQEggeIKAFLhADDQtQEAgOIBMMi3AhCgsQUAUOEHAAAqACDQ5VwAUuPx//8KIgBS4/L//xoAAKDjAZCg4wEAyOcJAKDhHNBL4vCPvegW8/7/8Egt6RCwjeIAMNHlAMCg4wBQoOMAAFPjFgAACgEQgeIBYKDjPSEA41zgoOM+QQDjXABT4yIAUxMFAAAaAgBV4QMAAMoF4MDnBnCg4QEwUeUAAADqBXCg4QcwwOcBUIfiATDR5AAAU+MCAAAKAmCH4gQAV+Ht//+6BcDA5/CIvegASC3pDbCg4QEgoOEAEKDhAwCg4wBIvehvAADqAEgt6Q2woOEBIKDhABCg4QMAoOMASL3oZAAA6gBILekNsKDhABCg4wEg0OcBEIHiAABS4/v//xoBAEHiAIi96ABILekNsKDhAOCg4QAAoOMAAFLjAIi9CAHA3uQBMNHkAwBc4QIAABoBIFLi+f//GgCIvegBAKDjAIi96ABILekNsKDhAIi96AAAAAAAAAAABOAt5QDmj+IQ6o7ixPG+5dTU1NTU1NTU1NTU1NTU1NQAxo/iEMqM4qzxvOXU1NTUAMaP4hDKjOKg8bzl1NTU1ADGj+IQyozilPG85dTU1NQAxo/iEMqM4ojxvOXU1NTUAMaP4hDKjOJ88bzl1NTU1ADGj+IQyozicPG85dTU1NQAxo/iEMqM4mTxvOXU1NTUAMaP4hDKjOJY8bzl1NTU1ADGj+IQyoziTPG85dTU1NQAxo/iEMqM4kDxvOXU1NTUAMaP4hDKjOI08bzl1NTU1ADGj+IQyoziKPG85dTU1NQAxo/iEMqM4hzxvOXU1NTUAMaP4hDKjOIQ8bzl1NTU1ADGj+IQyoziBPG85dTU1NQAxo/iEMqM4vjwvOXU1NTUAMaP4hDKjOLs8Lzl1NTU1ADGj+IQyozi4PC85dTU1NQBAAAAkgAAAB4AAAAIAAAA+///bwEAAAAXAAAAiAQAAAIAAACQAAAAAwAAAFgXAgAUAAAAEQAAAAYAAABUAQAACwAAABAAAAAFAAAAoAMAAAoAAACmAAAA9f7/b9wCAAAEAAAA+AIAAPD//2+UAgAA/v//b7wCAAD///9vAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkBUBAJAVAQCQFQEAkBUBAJAVAQCQFQEAkBUBAJAVAQCQFQEAkBUBAJAVAQCQFQEAkBUBAJAVAQCQFQEAkBUBAJAVAQCQFQEA//////////9Ib21lYnJldyBjbGFuZyB2ZXJzaW9uIDIxLjEuOABMaW5rZXI6IEhvbWVicmV3IExMRCAyMS4xLjgAQTsAAABhZWFiaQABMQAAAEMyLjA5AAYKB0EIAQkCCgMOAA8BEAERAhIEFAEVABcDGAEZARoCHgEiASYBAC5keW5zeW0ALmdudS52ZXJzaW9uAC5nbnUudmVyc2lvbl9yAC5nbnUuaGFzaAAuaGFzaAAuZHluc3RyAC5BUk0uZXhpZHgALnJlbC5wbHQALkFSTS5leHRhYgAucm9kYXRhAC50ZXh0AC5wbHQALmR5bmFtaWMALmdvdC5wbHQALnJlbHJvX3BhZGRpbmcALmRhdGEALmJzcwAuY29tbWVudAAuQVJNLmF0dHJpYnV0ZXMALnNoc3RydGFiAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAACwAAAAIAAABUAQAAVAEAAEABAAAGAAAAAQAAAAQAAAAQAAAACQAAAP///28CAAAAlAIAAJQCAAAoAAAAAQAAAAAAAAACAAAAAgAAABYAAAD+//9vAgAAALwCAAC8AgAAIAAAAAYAAAABAAAABAAAAAAAAAAlAAAA9v//bwIAAADcAgAA3AIAABwAAAABAAAAAAAAAAQAAAAAAAAALwAAAAUAAAACAAAA+AIAAPgCAACoAAAAAQAAAAAAAAAEAAAABAAAADUAAAADAAAAAgAAAKADAACgAwAApgAAAAAAAAAAAAAAAQAAAAAAAAA9AAAAAQAAcIIAAABIBAAASAQAAEAAAAALAAAAAAAAAAQAAAAAAAAASAAAAAkAAABCAAAAiAQAAIgEAACQAAAAAQAAAA4AAAAEAAAACAAAAFEAAAABAAAAAgAAABgFAAAYBQAAJAAAAAAAAAAAAAAABAAAAAAAAABcAAAAAQAAADIAAAA8BQAAPAUAAF8BAAAAAAAAAAAAAAEAAAABAAAAZAAAAAEAAAAGAAAAnAYBAJwGAADsDgAAAAAAAAAAAAAEAAAAAAAAAGoAAAABAAAABgAAAJAVAQCQFQAAQAEAAAAAAAAAAAAAEAAAAAAAAABvAAAABgAAAAMAAADQFgIA0BYAAIgAAAAGAAAAAAAAAAQAAAAIAAAAeAAAAAEAAAADAAAAWBcCAFgXAABUAAAAAAAAAAAAAAAEAAAAAAAAAIEAAAAIAAAAAwAAAKwXAgCsFwAAVAgAAAAAAAAAAAAAAQAAAAAAAACQAAAAAQAAAAMAAACsFwMArBcAAAgAAAAAAAAAAAAAAAQAAAAAAAAAlgAAAAgAAAADAAAAtBcDALQXAACQawAAAAAAAAAAAAAEAAAAAAAAAJsAAAABAAAAMAAAAAAAAAC0FwAAOgAAAAAAAAAAAAAAAQAAAAEAAACkAAAAAwAAcAAAAAAAAAAA7hcAADwAAAAAAAAAAAAAAAEAAAAAAAAAtAAAAAMAAAAAAAAAAAAAACoYAAC+AAAAAAAAAAAAAAABAAAAAAAAAA==
